### ISSUE TITLE
FusionSound repo missing

### ISSUE THREAD

**Issue by Greijus** [directfb2/FusionSound2#1]
Hi, 

I'm trying to compile an old project that uses DirectFB library. I was able to install DirectFB2 but when trying to compile this old project, I'm having trouble because it requires FusionSound as well. I'm not been able to find FusionSound.

Any idea where FusionSound repo can be found? or it will be uploaded in this FusionSound2 repo anytime soon?

Thank you!

**Comment by caramelli** [comment]
Yes, it is planned to restore the source code of FusionSound in this repository. Like DirectFB2, FusionSound2 uses the Meson build system.
I'm looking to push the code in the next few days.

**Comment by Greijus** [comment]
Awesome! Looking forward to it. Thanks!
