### ISSUE TITLE
ninja build fail for FusionSound2

### ISSUE THREAD

**Issue by Greijus** [directfb2/FusionSound2#3]
Hi, 

First of all, thank you for pushing this new FusionSound2 library and keeping the DirectFB project alive!

I'm trying to install the library but the  `ninja -C build/` failed. The `meson build/` worked just fine (just one warning):

```
$ meson build/
The Meson build system
Version: 1.0.0
Source dir: /media/stresstech/data/_debug/DirectFB/FusionSound2
Build dir: /media/stresstech/data/_debug/DirectFB/FusionSound2/build
Build type: native build
Project name: FusionSound2
Project version: 2.0.0
C compiler for the host machine: cc (gcc 9.4.0 "cc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0")
C linker for the host machine: cc ld.bfd 2.34
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Run-time dependency directfb-internal found: YES 2.0.0
Run-time dependency direct found: YES 2.0.0
Run-time dependency fusion found: YES 2.0.0
Checking for size of "long" : 8
Configuring config.h using configuration
Configuring fusionsound_version.h using configuration
Configuring fusionsound_build.h using configuration
Configuring build.h using configuration
Run-time dependency alsa found: YES 1.2.2
Has header "linux/soundcard.h" : YES 
Build targets in project: 6

Found ninja-1.10.0 at /usr/bin/ninja
WARNING: Running the setup command as `meson [options]` instead of `meson setup [options]` is ambiguous and deprecated.
```

The error:

```
$ ninja -C build/
ninja: Entering directory `build/'
[3/23] Compiling C object snddrivers/oss/libfusionsound_oss.so.p/oss.c.o
../snddrivers/oss/oss.c: In function ‘device_open’:
../snddrivers/oss/oss.c:210:84: warning: format not a string literal and no format arguments [-Wformat-security]
  210 |           snprintf( device_info->name, FS_SOUND_DEVICE_INFO_NAME_LENGTH, mixer_info.id );
      |                                                                          ~~~~~~~~~~^~~
[4/23] Compiling C object snddrivers/alsa/libfusionsound_alsa.so.p/alsa.c.o
../snddrivers/alsa/alsa.c: In function ‘device_open’:
../snddrivers/alsa/alsa.c:245:11: warning: format not a string literal and no format arguments [-Wformat-security]
  245 |           snprintf( device_info->name, FS_SOUND_DEVICE_INFO_NAME_LENGTH, snd_ctl_card_info_get_name( info ) );
      |           ^~~~~~~~
[8/23] Compiling C object src/libfusionsound-2.0.so.0.0.0.p/core_core_sound.c.o
FAILED: src/libfusionsound-2.0.so.0.0.0.p/core_core_sound.c.o 
cc -Isrc/libfusionsound-2.0.so.0.0.0.p -Isrc -I../src -I. -I.. -Iinclude -I../include -I/usr/local/include/directfb -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -O3 -fPIC '-DSYSCONFDIR="/usr/local/etc"' -MD -MQ src/libfusionsound-2.0.so.0.0.0.p/core_core_sound.c.o -MF src/libfusionsound-2.0.so.0.0.0.p/core_core_sound.c.o.d -o src/libfusionsound-2.0.so.0.0.0.p/core_core_sound.c.o -c ../src/core/core_sound.c
../src/core/core_sound.c:30:10: fatal error: fusion/shm/pool.h: No such file or directory
   30 | #include <fusion/shm/pool.h>
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
[13/23] Compiling C object src/libfusionsound-2.0.so.0.0.0.p/core_sound_buffer.c.o
ninja: build stopped: subcommand failed.

```
Do you have any idea how can I solve this? 

I'm attempting to this in Ubuntu 20.04. Thanks.

**Comment by caramelli** [comment]
Thanks for reporting your build logs: you're probably the first to play with FusionSound2 :-)

Regarding fusion/shm/pool.h, you probably need to update your DirectFB2 installation: https://github.com/directfb2/DirectFB2/commit/7da29a843e2a765f53c87874c7ffdc37a2312f51

**Comment by Greijus** [comment]
I pulled the latest version of DirectFB2 and tried the usual installation process but it didn't worked. So, I guess that first I need to uninstall it, but not sure how to uninstall with ninja. Please, could you give some advice here?

Also, should I use the specific commit you provided in the link, or it will work with the latest available code in master?

**Comment by caramelli** [comment]
Yes, you can use the latest version of DirectFB2 by running in a Terminal of your Ubuntu distribution:

  $ meson build/
  $ ninja -C build/
  $ sudo ninja -C build/ install

This will install DirectFB2 in /usr/local, the previous version is just overwritten.

Same for FusionSound2: make sure libasound2-dev package is installed on your Ubuntu distribution (in order to build FusionSound2 with ALSA sound driver support).

Then you can check the fs_buffer or fs_stream examples available in [DirectFB-examples](https://github.com/directfb2/DirectFB-examples)

If you get any errors, feel free to report it.

**Comment by Greijus** [comment]
For some reason is failing to re-install DirectFB2. This is the log:

```
$ sudo ninja -C build/ install
[sudo] password for stresstech: 
ninja: Entering directory `build/'
[0/1] Installing files.
Traceback (most recent call last):
  File "/home/stresstech/.local/bin/meson", line 5, in <module>
    from mesonbuild.mesonmain import main
ModuleNotFoundError: No module named 'mesonbuild'
FAILED: meson-internal__install 
/home/stresstech/.local/bin/meson install --no-rebuild
ninja: build stopped: subcommand failed.
``` 
The only difference to previous time I installed DirectFB2 succesfully, is that I upgraded meson to version 1.0.0 through "pip3 install meson" as required by FusionSound2. Then I created a symlink in /usr/bin/ to `/home/stresstech/.local/bin/meson`  and also added `$ PATH="/home/stresstech/.local/bin:$PATH"`, since pip3 installs packages in locations that the systems doesn't find.

Thank you for the timely support :)

**Comment by caramelli** [comment]
This seems to be a problem with the meson installation.
What you can easily try (this is how I do with meson on a Linux distribution):

	wget https://github.com/mesonbuild/meson/releases/download/0.61.5/meson-0.61.5.tar.gz
	tar xf meson-0.61.5.tar.gz
	cd meson-0.61.5
	sudo python3 ./setup.py install

This will install meson in /usr/local which should now be used when calling meson from the command line.

**Comment by Greijus** [comment]
It worked! By upgrading meson the way you suggested, I was able to re-install DirectFB2, and then installed FusionSound2. Finally, I opened a virtual console (tty3) and runned succesfully `fs_buffer `and `fs_stream `examples. The examples also can be executed in the normal terminal in Ubuntu 20.04.

Thanks!!

**Comment by eli-schwartz** [comment]
> Then I created a symlink in /usr/bin/ to `/home/stresstech/.local/bin/meson` and also added `$ PATH="/home/stresstech/.local/bin:$PATH"`, since pip3 installs packages in locations that the systems doesn't find.

But once you ran `sudo ninja install` it attempted to run meson as root, so the symlink existed, but your PATH modifications didn't -- and most critically, `/home/stresstech/.local/lib/python3.X/site-packages` wasn't part of the root import path. :)

This caveat is documented at https://mesonbuild.com/Getting-meson.html#installing-meson-with-pip
